//! Rasterwarp: real-time analog video-synthesis animation.

pub mod app;
pub mod blend;
pub mod canvas;
pub mod capture;
pub mod clock;
pub mod control;
pub mod curve;
pub mod curve_editor;
pub mod files_ui;
pub mod fringe;
pub mod gpu;
pub mod inputs;
pub mod inputs_ui;
pub mod midi;
pub mod motion;
pub mod params;
pub mod passes;
pub mod presets;
pub mod preview;
pub mod rate;
pub mod save;
pub mod sequence;
pub mod session;
pub mod source;
pub mod transition;
pub mod ui;
pub mod video;
